# Car Project

## Data Explorations and Analysis

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(color_codes=True)
%matplotlib inline

In [2]:
df = pd.read_csv('dataset/car.data',header=-1)

In [3]:
df2 = pd.read_csv('dataset/car.data')

In [4]:
df.head()

       0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [5]:
df2.head()

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [6]:
col_name = ['buying','maint','doors','person','lug_boot','safety','class']
df.columns=col_name
df.head(10)

  buying  maint doors person lug_boot safety  class
0  vhigh  vhigh     2      2    small    low  unacc
1  vhigh  vhigh     2      2    small    med  unacc
2  vhigh  vhigh     2      2    small   high  unacc
3  vhigh  vhigh     2      2      med    low  unacc
4  vhigh  vhigh     2      2      med    med  unacc
5  vhigh  vhigh     2      2      med   high  unacc
6  vhigh  vhigh     2      2      big    low  unacc
7  vhigh  vhigh     2      2      big    med  unacc
8  vhigh  vhigh     2      2      big   high  unacc
9  vhigh  vhigh     2      4    small    low  unacc

## Car Data from Seaborn

In [3]:
car = sns.load_dataset('car')

HTTPError: HTTP Error 404: Not Found

In [15]:
car.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa